### PR TITLE
Improved cmake installation

### PR DESCRIPTION
**Pull request by WorldSEnder**
This fixes several things related to a correct cmake installation:

- hyproConfig.cmake files are installed to the system wide registry (/usr/lib/cmake/... on unix)

- EXPORT_TO_CMAKE: an entry in the user package registry is only made when switch is on.

- cleaning up load_library macro

- include path is now correct for both a user export and aystem wide installation.

- GLPK is discovered if present

EDIT: I will squash the commits into one once the travis builds pass

### CODE REVIEW

**Comment by WorldSEnder** [comment]
Don't merge yet, at least until the travis tests run through. Judging from the logs, the reason for failure is currently carl's include directories not being exported correctly.

**Comment by modass** [comment]
Yes - I am still reviewing your changes. Thanks though, these look good so far. However we require to use that specific, *shipped* version of glpk, as it is patched to be thread-safe.

**Comment by WorldSEnder** [comment]
Wouldn't you also need to either link statically against or install the modified version of glpk, then?

**Comment by modass** [comment]
I think linking statically would be nicer, but yes, you are right.

**Comment by modass** [comment]
Apart from the last build on OSX everything seems to be fine now - I am currently trying to find out what's wrong for the last build and after that I think we can merge.

**Comment by WorldSEnder** [comment]
The build depends on a pull request on carl, which is currently also pending, see https://github.com/smtrat/carl/pull/15

**Comment by modass** [comment]
I could not reproduce the error for OSX on our machines - I will temporarily add more recent OSX images and allow this one (xcode6.4) to fail.

**Comment by WorldSEnder** [comment]
One last thing, you'd have to undo my modifications to the .travis.yml since I only changed that to depend on the (then not merged) change to carl

**Comment by modass** [comment]
Oh - thanks, did not see that! Thank you for your help anyway, appreciated that a lot!

**Pull request merged**
